spring:
  application:
    name: user_service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
## Generate API key from https://home.openweathermap.org/api_keys
openweathermap:
  api:
    key=YOUR_API_KEY: